login:
  path:              /login
  defaults:             { _controller: IMAGLdapBundle:Default:login }
  requirements:
    methods:            [GET]

login_check:
  path:              /login_check

logout:
  path:              /logout
