login:
  path:              /login
  defaults:             { _controller: IMAGLdapBundle:Default:login }
  requirements:
    _method:            GET

login_check:
  path:              /login_check

logout:
  path:              /logout
